const OFFERS=["Letramento IA #4","Letramento de Ferramentas de IA","Letramento IA — Segmento Saúde","Letramento IA Nível 2 — Automação, APP, RAG, Cultura + Laboratório"];
const STAGES=["Lead","Contato iniciado","Diagnóstico","Proposta enviada","Negociação","Confirmada","Perdida"];
const PROB={"Lead":10,"Contato iniciado":20,"Diagnóstico":40,"Proposta enviada":60,"Negociação":80,"Confirmada":100,"Perdida":0};
const TEMPERATURES=["Quente","Morno","Frio"];
const TEMP_META={Quente:{icon:"🔥",className:"hot"},Morno:{icon:"☀️",className:"warm"},Frio:{icon:"❄️",className:"cold"}};
const STORAGE="crm-letramento-iprocesso-v1";
const seed=[
 {id:"DEMO-001",empresa:"Empresa Exemplo A",contato:"Contato Comercial",email:"",telefone:"",oferta:OFFERS[0],evento:"Turma Demonstrativa",responsavel:"Vendedor 1",etapa:"Negociação",temperatura:"Quente",pessoasPrevistas:5,pessoasConfirmadas:3,valorTotal:5000,probabilidade:80,mesPrevisto:currentMonth(),proximaAcao:"Confirmar participantes e condições",dataProximaAcao:offsetDate(2),ultimoContato:offsetDate(-2),origem:"Demonstração",observacoes:"Dados fictícios"},
 {id:"DEMO-002",empresa:"Clínica Exemplo B",contato:"Gestão",email:"",telefone:"",oferta:OFFERS[2],evento:"Turma Saúde Demonstrativa",responsavel:"Vendedor 2",etapa:"Proposta enviada",temperatura:"Morno",pessoasPrevistas:12,pessoasConfirmadas:0,valorTotal:9800,probabilidade:60,mesPrevisto:currentMonth(),proximaAcao:"Apresentar escopo e agenda",dataProximaAcao:offsetDate(4),ultimoContato:offsetDate(-5),origem:"Demonstração",observacoes:"Dados fictícios"},
 {id:"DEMO-003",empresa:"Empresa Exemplo C",contato:"Responsável",email:"",telefone:"",oferta:OFFERS[1],evento:"Ferramentas de IA",responsavel:"Vendedor 1",etapa:"Diagnóstico",temperatura:"Frio",pessoasPrevistas:8,pessoasConfirmadas:0,valorTotal:6400,probabilidade:40,mesPrevisto:currentMonth(),proximaAcao:"Mapear ferramentas atuais",dataProximaAcao:offsetDate(-1),ultimoContato:offsetDate(-8),origem:"Demonstração",observacoes:"Dados fictícios"}
];
let opportunities=loadLocal();let filters={month:currentMonth(),owner:"",event:"",stage:"",product:"",temperature:"",search:""};
let currentView=localStorage.crmView||"list";
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
document.addEventListener("DOMContentLoaded",()=>{initControls();bindEvents();render();registerSW();setupGoogleAuth();if(localStorage.apiUrl&&localStorage.accessMode!=="google")syncFromSheet(false)});
function currentMonth(){return new Date().toISOString().slice(0,7)}function offsetDate(n){const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function loadLocal(){try{return JSON.parse(localStorage.getItem(STORAGE))||seed}catch{return seed}}function saveLocal(){localStorage.setItem(STORAGE,JSON.stringify(opportunities))}
function initControls(){const mf=$("#monthFilter");mf.innerHTML='<option value="">Todos os meses</option>';for(let i=-6;i<=12;i++){const v=monthOffset(i);mf.insertAdjacentHTML("beforeend",`<option value="${v}">${monthLabel(v)}</option>`)}mf.value=filters.month;fillSelect('[name="oferta"]',OFFERS);fillSelect('[name="etapa"]',STAGES);fillSelect("#stageFilter",STAGES,true);renderQuickFilters();setView(currentView,false);refreshDynamicFilters()}
function fillSelect(selector,values,keep=false){const el=$(selector);const first=keep?el.innerHTML:"";el.innerHTML=first+values.map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join("")}
function refreshDynamicFilters(){const owner=$("#ownerFilter"),event=$("#eventFilter"),ov=owner.value,ev=event.value;owner.innerHTML='<option value="">Todos</option>'+unique(opportunities.map(x=>x.responsavel)).map(option).join("");event.innerHTML='<option value="">Todos</option>'+unique(opportunities.flatMap(x=>[x.evento,x.oferta])).map(option).join("");owner.value=ov;event.value=ev}
function option(v){return`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`}function unique(a){return[...new Set(a.filter(Boolean))].sort((a,b)=>a.localeCompare(b,"pt-BR"))}
function bindEvents(){[["#monthFilter","month"],["#ownerFilter","owner"],["#eventFilter","event"],["#stageFilter","stage"],["#searchFilter","search"]].forEach(([sel,key])=>$(sel).addEventListener("input",e=>{filters[key]=e.target.value;render()}));$("#newBtn").onclick=()=>openForm();$("#exportBtn").onclick=exportCsv;$("#settingsBtn").onclick=openSettings;$("#syncBtn").onclick=()=>syncFromSheet(true);$("#listViewBtn").onclick=()=>setView("list");$("#kanbanViewBtn").onclick=()=>setView("kanban");$("#opportunityForm").addEventListener("submit",saveForm);$("#settingsForm").addEventListener("submit",saveSettings);$("#deleteBtn").onclick=deleteCurrent}
function filtered(){const q=filters.search.trim().toLowerCase();return opportunities.filter(o=>(!filters.month||o.mesPrevisto===filters.month)&&(!filters.owner||o.responsavel===filters.owner)&&(!filters.event||o.evento===filters.event||o.oferta===filters.event)&&(!filters.stage||o.etapa===filters.stage)&&(!filters.product||o.oferta===filters.product)&&(!filters.temperature||temperatureOf(o)===filters.temperature)&&(!q||[o.empresa,o.contato,o.oferta,o.evento,o.proximaAcao].join(" ").toLowerCase().includes(q)))}
function render(){const data=filtered();$("#periodLabel").textContent=filters.month?`${monthLabel(filters.month)} · visão consolidada do pipeline comercial.`:"Todos os meses · visão consolidada do pipeline comercial.";renderKpis(data);renderFunnel(data);renderActions(data);renderEvents(data);renderRows(data);renderKanban(data);renderQuickFilters();refreshDynamicFilters()}
function renderKpis(d){const pipeline=sum(d,"valorTotal"),weighted=d.reduce((s,x)=>s+num(x.valorTotal)*num(x.probabilidade)/100,0),confirmed=d.filter(x=>x.etapa==="Confirmada"),pPrev=sum(d,"pessoasPrevistas"),pConf=sum(d,"pessoasConfirmadas");const items=[["Pipeline total",money(pipeline),`${d.length} oportunidade${d.length===1?"":"s"}`],["Pipeline ponderado",money(weighted),"Valor × probabilidade"],["Receita confirmada",money(sum(confirmed,"valorTotal")),`${confirmed.length} fechada${confirmed.length===1?"":"s"}`],["Pessoas previstas",fmt(pPrev),`${fmt(pConf)} confirmada${pConf===1?"":"s"}`],["Taxa de confirmação",pct(pPrev?pConf/pPrev*100:0),"Participantes confirmados"]];$("#kpis").innerHTML=items.map(x=>`<article class="card kpi"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join("")}
function renderFunnel(d){const counts=STAGES.map(s=>({s,n:d.filter(x=>x.etapa===s).length,v:sum(d.filter(x=>x.etapa===s),"valorTotal")}));const max=Math.max(1,...counts.map(x=>x.n));$("#funnel").innerHTML=counts.map(x=>`<div class="funnel-row"><span>${x.s}</span><div class="funnel-bar"><i style="width:${x.n/max*100}%"></i></div><strong>${x.n} · ${compactMoney(x.v)}</strong></div>`).join("")}
function renderActions(d){const active=d.filter(x=>x.dataProximaAcao&&!["Confirmada","Perdida"].includes(x.etapa)).sort((a,b)=>a.dataProximaAcao.localeCompare(b.dataProximaAcao)).slice(0,8);$("#nextActions").innerHTML=active.length?active.map(x=>`<button class="action ${x.dataProximaAcao<offsetDate(0)?"overdue":""}" onclick="editOpportunity('${x.id}')"><strong>${escapeHtml(x.empresa)}</strong><span>${dateLabel(x.dataProximaAcao)} · ${escapeHtml(x.proximaAcao||"Definir próxima ação")}</span></button>`).join(""):'<p class="muted">Nenhuma ação pendente neste filtro.</p>'}
function renderEvents(d){const groups={};d.forEach(x=>{const k=x.evento||x.oferta||"Sem evento";groups[k]??=[];groups[k].push(x)});$("#eventsSummary").innerHTML=Object.entries(groups).length?Object.entries(groups).map(([k,v])=>`<article class="event-card"><h3>${escapeHtml(k)}</h3><div class="event-metrics"><div><span>Previstas</span><strong>${sum(v,"pessoasPrevistas")}</strong></div><div><span>Confirmadas</span><strong>${sum(v,"pessoasConfirmadas")}</strong></div><div><span>Pipeline</span><strong>${compactMoney(sum(v,"valorTotal"))}</strong></div><div><span>Conversão</span><strong>${pct(sum(v,"pessoasPrevistas")?sum(v,"pessoasConfirmadas")/sum(v,"pessoasPrevistas")*100:0)}</strong></div></div></article>`).join(""):'<p class="muted">Nenhuma oportunidade encontrada.</p>'}
function renderRows(d){$("#resultCount").textContent=`${d.length} registro${d.length===1?"":"s"}`;$("#opportunitiesTable").innerHTML=d.map(x=>`<tr class="clickable-row" onclick="editOpportunity('${x.id}')"><td><strong>${tempBadge(x)} ${escapeHtml(x.empresa)}</strong><small>${escapeHtml(x.contato||"")}</small></td><td><strong>${escapeHtml(x.evento||x.oferta)}</strong><small>${escapeHtml(x.oferta)}</small></td><td>${escapeHtml(x.responsavel)}</td><td><span class="stage">${escapeHtml(x.etapa)}</span></td><td class="person-count">👥 ${num(x.pessoasConfirmadas)} / ${num(x.pessoasPrevistas)}</td><td class="money">💰 ${money(x.valorTotal)}<small>🎟️ ${money(ticket(x))}</small></td><td><strong>${escapeHtml(x.proximaAcao||"—")}</strong><small>${dateLabel(x.dataProximaAcao)}</small></td><td><button class="btn ghost" onclick="event.stopPropagation();editOpportunity('${x.id}')">Editar</button></td></tr>`).join("");$("#opportunitiesCards").innerHTML=d.map(oppCard).join("")}
function renderKanban(d){$("#kanbanBoard").innerHTML=STAGES.map(stage=>{const items=d.filter(x=>x.etapa===stage),total=sum(items,"valorTotal");return`<section class="kanban-column"><header><div><strong>${escapeHtml(stage)}</strong><span>${items.length} oportunidade${items.length===1?"":"s"}</span></div><b>${compactMoney(total)}</b></header><div class="kanban-stack">${items.length?items.map(kanbanCard).join(""):'<p class="kanban-empty">Nenhuma oportunidade</p>'}</div></section>`}).join("")}
function kanbanCard(x){return`<article class="kanban-card" tabindex="0" role="button" onclick="editOpportunity('${x.id}')" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();editOpportunity('${x.id}')}" aria-label="Editar ${escapeHtml(x.empresa)}"><div class="opp-card-head"><span class="temp-badge ${tempClass(x)}">${tempIcon(x)} ${escapeHtml(temperatureOf(x))}</span><span class="probability">${num(x.probabilidade)}%</span></div><h3>${escapeHtml(x.empresa)}</h3><p class="product-name">${escapeHtml(shortOffer(x.oferta))}</p><div class="card-metrics"><span title="Pessoas confirmadas e previstas">👥 <b>${num(x.pessoasConfirmadas)}/${num(x.pessoasPrevistas)}</b></span><span title="Valor da oportunidade">💰 <b>${compactMoney(x.valorTotal)}</b></span><span title="Ticket médio por pessoa">🎟️ <b>${compactMoney(ticket(x))}</b></span></div><div class="kanban-next"><span>${escapeHtml(x.responsavel||"Sem responsável")}</span><small>${dateLabel(x.dataProximaAcao)}</small></div></article>`}
function oppCard(x){return`<article class="opp-card" onclick="editOpportunity('${x.id}')"><div class="opp-card-head"><strong>${escapeHtml(x.empresa)}</strong><span class="temp-badge ${tempClass(x)}">${tempIcon(x)} ${escapeHtml(temperatureOf(x))}</span></div><p>${escapeHtml(x.evento||x.oferta)}</p><div class="card-metrics"><span>👥 <b>${num(x.pessoasConfirmadas)}/${num(x.pessoasPrevistas)}</b></span><span>💰 <b>${compactMoney(x.valorTotal)}</b></span><span>🎟️ <b>${compactMoney(ticket(x))}</b></span></div><div class="opp-card-foot"><span class="stage">${escapeHtml(x.etapa)}</span><small>${dateLabel(x.dataProximaAcao)}</small></div></article>`}
function renderQuickFilters(){const products=[["","Todos"],...OFFERS.map((x,i)=>[x,["IA #4","Ferramentas","Saúde","Nível 2"][i]])];$("#productChips").innerHTML=products.map(([v,l])=>chip("product",v,l,v?"◆":"◎",filters.product===v)).join("");const months=[["","Todos"],...[0,1,2,3].map(i=>{const v=monthOffset(i);return[v,i===0?"Mês atual":monthLabelShort(v)]})];$("#monthChips").innerHTML=months.map(([v,l])=>chip("month",v,l,"▣",filters.month===v)).join("");const temps=[["","Todas"],...TEMPERATURES.map(x=>[x,x])];$("#temperatureChips").innerHTML=temps.map(([v,l])=>chip("temperature",v,l,v?TEMP_META[v].icon:"◎",filters.temperature===v)).join("")}
function chip(key,value,label,icon,active){return`<button type="button" class="chip ${active?"active":""}" aria-pressed="${active}" onclick="setQuickFilter('${key}','${value}')">${icon} ${escapeHtml(label)}</button>`}
window.setQuickFilter=(key,value)=>{filters[key]=value;if(key==="month")$("#monthFilter").value=value;render()};
function setView(view,persist=true){currentView=view;const kanban=view==="kanban";$("#kanbanBoard").classList.toggle("hidden",!kanban);$(".table-wrap").classList.toggle("hidden",kanban);$("#opportunitiesCards").classList.toggle("view-hidden",kanban);[["#listViewBtn",!kanban],["#kanbanViewBtn",kanban]].forEach(([s,on])=>{$(s).classList.toggle("active",on);$(s).setAttribute("aria-pressed",String(on))});if(persist)localStorage.crmView=view}
function openForm(data={}){const f=$("#opportunityForm");f.reset();Object.entries(data).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v??""});if(!data.id){f.elements.mesPrevisto.value=filters.month||currentMonth();f.elements.probabilidade.value=20;f.elements.etapa.value="Lead";f.elements.temperatura.value="Morno"}else if(!data.temperatura)f.elements.temperatura.value=temperatureOf(data);$("#dialogTitle").textContent=data.id?"Editar oportunidade":"Nova oportunidade";$("#deleteBtn").classList.toggle("hidden",!data.id);$("#opportunityDialog").showModal()}window.editOpportunity=id=>openForm(opportunities.find(x=>x.id===id));
async function saveForm(e){e.preventDefault();const f=e.target,obj=Object.fromEntries(new FormData(f));["pessoasPrevistas","pessoasConfirmadas","valorTotal","probabilidade"].forEach(k=>obj[k]=num(obj[k]));obj.probabilidade=obj.probabilidade||PROB[obj.etapa];obj.id=obj.id||`OP-${Date.now().toString().slice(-8)}`;obj.updatedAt=new Date().toISOString();const i=opportunities.findIndex(x=>x.id===obj.id);if(i>=0)opportunities[i]={...opportunities[i],...obj};else opportunities.unshift({...obj,createdAt:obj.updatedAt});saveLocal();f.closest("dialog").close();render();await pushChange(i>=0?"update":"create",obj);toast("Oportunidade salva.")}
async function deleteCurrent(){const id=$("#opportunityForm").elements.id.value;if(!id||!confirm("Excluir esta oportunidade?"))return;opportunities=opportunities.filter(x=>x.id!==id);saveLocal();$("#opportunityDialog").close();render();await pushChange("delete",{id});toast("Oportunidade excluída.")}
function openSettings(){const f=$("#settingsForm");f.elements.accessMode.value=localStorage.accessMode||"google";f.elements.apiUrl.value=localStorage.apiUrl||"";f.elements.googleClientId.value=localStorage.googleClientId||"";f.elements.apiKey.value="";$("#settingsDialog").showModal()}async function saveSettings(e){e.preventDefault();localStorage.accessMode=e.target.elements.accessMode.value;localStorage.apiUrl=e.target.elements.apiUrl.value.trim();localStorage.googleClientId=e.target.elements.googleClientId.value.trim();sessionStorage.apiKey=e.target.elements.apiKey.value;sessionStorage.removeItem("googleIdToken");e.target.closest("dialog").close();setupGoogleAuth();if(localStorage.accessMode==="key")await syncFromSheet(true);else toast("Configuração salva. Entre com sua conta Google.")}
async function api(action,payload={}){const url=localStorage.apiUrl,mode=localStorage.accessMode||"key",key=sessionStorage.apiKey,idToken=sessionStorage.googleIdToken;if(!url)throw new Error("Configure a URL do Google Apps Script.");if(mode==="google"&&!idToken)throw new Error("Entre com sua conta Google para acessar os dados.");const res=await fetch(url,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,key,idToken,payload})});const out=await res.json();if(!out.ok)throw new Error(out.error||"Falha na integração.");return out.data}
function setupGoogleAuth(attempt=0){const host=$("#googleSignIn");if(!host)return;host.innerHTML="";if((localStorage.accessMode||"key")!=="google"||!localStorage.googleClientId)return;if(!window.google?.accounts?.id){if(attempt<20)setTimeout(()=>setupGoogleAuth(attempt+1),500);return}google.accounts.id.initialize({client_id:localStorage.googleClientId,callback:async r=>{sessionStorage.googleIdToken=r.credential;$("#connectionStatus").textContent="Login Google confirmado";await syncFromSheet(true)}});google.accounts.id.renderButton(host,{theme:"outline",size:"medium",text:"signin_with",shape:"pill"});if(!sessionStorage.googleIdToken)$("#connectionStatus").textContent="Login Google necessário"}
async function syncFromSheet(notify=true){try{$("#connectionStatus").textContent="Sincronizando...";const data=await api("list");if(Array.isArray(data)){opportunities=data;saveLocal();render()}$("#connectionStatus").textContent="Google Sheets conectado";if(notify)toast("Dados sincronizados com a planilha.")}catch(e){$("#connectionStatus").textContent="Modo local";if(notify)toast(e.message,true)}}async function pushChange(action,payload){if(!localStorage.apiUrl)return;try{await api(action,payload);$("#connectionStatus").textContent="Google Sheets conectado"}catch(e){toast(`Salvo localmente. ${e.message}`,true)}}
function exportCsv(){const d=filtered(),keys=["id","empresa","contato","email","telefone","oferta","evento","responsavel","etapa","temperatura","pessoasPrevistas","pessoasConfirmadas","valorTotal","probabilidade","mesPrevisto","proximaAcao","dataProximaAcao","ultimoContato","origem","observacoes"];const csv=[keys,...d.map(x=>keys.map(k=>x[k]??""))].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(";")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv"}));a.download=`crm-letramento-${filters.month||"completo"}.csv`;a.click();URL.revokeObjectURL(a.href)}
function registerSW(){if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{})}function sum(a,k){return a.reduce((s,x)=>s+num(x[k]),0)}function num(v){return Number(v)||0}function fmt(v){return new Intl.NumberFormat("pt-BR").format(v)}function money(v){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(num(v))}function compactMoney(v){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",notation:"compact",maximumFractionDigits:1}).format(num(v))}function pct(v){return`${Math.round(v)}%`}function monthOffset(i){const d=new Date();d.setDate(1);d.setMonth(d.getMonth()+i);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`}function monthLabel(v){if(!v)return"";const[y,m]=v.split("-");return new Date(+y,+m-1,1).toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}function monthLabelShort(v){const[y,m]=v.split("-");return new Date(+y,+m-1,1).toLocaleDateString("pt-BR",{month:"short",year:"2-digit"}).replace(" de ","/")}function dateLabel(v){if(!v)return"Sem data";return new Date(v+"T12:00:00").toLocaleDateString("pt-BR")}function ticket(x){const people=num(x.pessoasPrevistas)||num(x.pessoasConfirmadas);return people?num(x.valorTotal)/people:0}function temperatureOf(x){return TEMPERATURES.includes(x.temperatura)?x.temperatura:num(x.probabilidade)>=70?"Quente":num(x.probabilidade)>=40?"Morno":"Frio"}function tempIcon(x){return TEMP_META[temperatureOf(x)].icon}function tempClass(x){return TEMP_META[temperatureOf(x)].className}function tempBadge(x){return`<span class="temp-dot ${tempClass(x)}" title="${temperatureOf(x)}">${tempIcon(x)}</span>`}function shortOffer(v=""){return v.replace("Letramento IA — ","").replace("Letramento de ","")}function escapeHtml(v=""){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}function toast(msg,error=false){const t=$("#toast");t.textContent=msg;t.className=`toast show${error?" error":""}`;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.className="toast",3500)}
